{% set version = "2.3.0" %}

package:
  name: r-mapdata
  version: {{ version|replace("-", "_") }}

source:
  fn: mapdata_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mapdata_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mapdata/mapdata_{{ version }}.tar.gz
  sha256: 1edc180990387b6b1cd4e43a9505ebeb98e6115e4205c4f32f05b397c781dd76

build:
  number: 0
  script:
    - set TARGET_ARCH=  # [win]
    - R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-maps >=2.0_7
    - posix  # [win]
    - m2w64-toolchain  # [win64]
    - gcc  # [not win]
  run:
    - r-base
    - r-maps >=2.0_7

test:
  commands:
    - R -e "library('mapdata')"  # [not win]
    - R -e \"library('mapdata')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mapdata
  license: GPL-2
  summary: Supplement to maps package, providing the larger and/or higher-resolution databases.
  license_family: GPL2

extra:
  recipe-maintainers:
    - ocefpaf
