{% set version = '2.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapdata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapdata/mapdata_{{ version }}.tar.gz
  sha256: 1edc180990387b6b1cd4e43a9505ebeb98e6115e4205c4f32f05b397c781dd76

build:
  merge_build_host: True  # [win]
  number: 1005
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}sed  # [win]
    - {{ posix }}coreutils  # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-maps >=2.0_7
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-maps >=2.0_7

test:
  commands:
    - $R -e "library('mapdata')"           # [not win]
    - "\"%R%\" -e \"library('mapdata')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mapdata
  license: GPL-2
  summary: Supplement to maps package, providing the larger and/or higher-resolution databases.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
