travis:
  secure:
    BINSTAR_TOKEN: hDf7Y/IEXFLusLqBNmYJyO8iMOyqMX+F+uEiNtqPxNfCMf57PUROUnSKR13yVaHn49A445NeFjquQvL3y+f6tHD3+1eSMJ5EvU7DLhTh+HimuKuehWSo6pmb5/vVIJrN4FTe1VrbrmXYFqoi21NoUpJDweBY+6O6ocZrBRZR55Y3a1x+yeMtqEUOpA7Vm+/Uto4YlQsp5wiedwBsXRSfvaJ2lc//h/ozBtq77N3mT9G2YoV+AiTEX5Tr34l4+4458T5ghtymYIj6sI2a9c3x/JR8VlK3zLhHLhUefPZKnLfiZuj6IaOU7juw5bdmXBR6yMHGfuZCoPhlSEK1FY+58cd0v68GGQYNciSXLitHMiPNAADgIUal6ahSUX60X8pH/OS5wMGcLyr1K86KBa2dyW9sPE2zAfhrEGlSpczxbx2oE8ZcTUDgZzCrvw4T9DCL6nzvbVsjJ12aLWrmxz7LdLuz6ZJN67VduelCfwn5cSYAlKi23LsFzNqt5TnyIQjrnwv7Vfk/KHxCKOSiATJeub6Ac42Nzc7cIloMZQdSCvvA3F7E6feirnDaK7AemRhng8dwKV5zNZ9s684gXp9HSViYIHZVhqhZgp3UIBmV/g1xWDBFeUQvybBXuz4DU7Ziotv6ZXsuxk44JwKpl1CF/SFFSBUDKyEGllBK1ZrgzQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
