appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Po3Ks4I3JrCL9HjNsFXiSSMZtw3KlFVpFsQnouzXuu0qzs7gSbpeprV7jwQHP1PSRCwWahpWa2EN4AxBU7pA7JzuGQKc0JV621XNoTp7BdnuSbN4BUsha5NBvuTBCKvgoboJ0qvf1Rwra3LUdOb/OIrCa2TPmnfLV0hjZuI3JzXQfrLwzwTUY8X2lLMgH6mW3FrfM9qmbLPxxYrNJ6yojiSYIa2dDxl4+a6lAItqKCCzw/bfzSok8+H0ysZDYwv+CEqVIsr/fvQouI3mPaCwEE/r7PMQ3i4QOTnzcTQTsQbXryqGlDC1PPfBGXebYW3MyqQkPaYrcHiZ3uXuCEhEF1ImXpiemSMXcNIrDpO99O+aVaH4wnXCls5D2UflRcWOTNGQTUi1zcGe8wrmO7zVxaoLwJzp2VBSYQG3VHGY+CIMJHAOqXD9irQHhYwfwklvxI+hkbx4G5ElHgf5bfbqLlQLrp4J5b1PRxGY9L6KIHxk3LXGqpVto81LcqId6Byz7eWJ4Os29QwZcZtnD8JpCZf8iussOBuXMC0sEZP9xaNA4+VPv3Qe9kQ5ZkvMjbS7hW1fp36LljZ+HVpfOKsqUM+S0oDA+3EtyW+vR8/UxZy696yNj0ijfv5RiUaBGQmGrFVQuf0R9mYGRFDCUVeABtsiW/D14JrJW1nX60CgaGc=
conda_forge_output_validation: true
