travis:
  secure:
    BINSTAR_TOKEN: hqRa/UaHiUIRnvDP3bQOEgZi9SsJJ4j1nPS0Aly+b0IZjxhb0TK978D44a3VYAHD6lERi670y3YvN6/4y1523x+imA7pAxGp65RwWJgh8lR060gBTDqcRSRX2yYfjlTHEWZxWJzu5N+oPsaNy58p08tEZ4Oe+H1uuQxBaswp41IKVwZ8sKvnAhfMVsc6nUNrq94ARLV8MklOxDN4Erq9upkV0M5xM9BkQ7VQ47dZfCPW3iu+5pn1jitusMx9vhBHN+DKRa6n97ftAcSyGaed+IfHPQA820XGt3l3XmWrC69hb8/QFEr23pSwXZ1KQ6OHUFuu8mhaUMeMwcz/l/49BKktjWpNhbsNB3bbKOxCJdIj+jClfd2SS51Ja6dEUPEAq1QzZbxQApax1QGQZzvh+g9HYIc2XhkTrONnCe1fYmkHTdTYZZt64u9R9vL+4q6HDSHwOgG3TlerhFvcHiSn4YhHnjK/AS8hfUWFDl+8y5cVCfF3bPoxzywnf+40/Ip4+fPif8rG3cR3HkWu+xjFIWWMSA91RYaR9xbLvnxhYKh5PnLcZPGY3rg8RGDnXEj4r1EX6F9Ft1QFWWWrJOSygevY+afj/3vxZ9MWohjpc613rPDjFOo0cBNnx4uYPEFtf4a/B5b+++sGNxKj5gI4QXWlCkpKewmhf4kX9e2s3X0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
